---
baseURL: https://workischanging.co.uk/
languageCode: en-us
title: WORK IS CHANGING
pygmentsstyle: monokai
taxonomies:
  author: authors
enableEmoji: true
imaging:
  anchor: Smart
  bgColor: '#ffffff'
  hint: photo
  quality: 1
  resampleFilter: Box
